# Generated by Django 3.2.4 on 2021-08-10 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210809_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0, message='Hours should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100.0, message='Price must be greater than 100.00 !!'), django.core.validators.MaxValueValidator(200.0, message='Price must be less than 200.00 !!')]),
        ),
    ]
